title: Köy Odası
keywords: Köy Odası, Blog
description: Köy Odası Tanıtım Sayfası
baseurl:
url: https://koy-odasi.github.io
permalink: "/categories/:categories/:title/"
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions:
  - smart
author: koy-odasi
editor: vim
email: 
cv: 
disqus: 
github: koy-odasi
trello: 
linkedin: 
googletagid: 
twitter: 
facebook: 
instagram: 
foursquare: 
stack: 
